---
# ydbd dynamic nodes configuration

- name: Copy cluster configuration file
  copy: src={{ ydb_config }} dest={{ ydb_dir }}/cfg/ydbd-config.yaml
  when: ydb_config is defined

- name: Build dynamic node configuration file
  command: "{{ ydb_dir }}/home/update_config_file.sh ydbd-config.yaml ydbd-dynamic.yaml COMPUTE {{ ydb_cores_dynamic }}"
  when: ydb_config is defined and ydb_cores_dynamic is defined
