- name: wait for multi-user.target
  shell: systemctl -q is-active multi-user.target
  register: result
  until: result.rc == 0
  retries: 60
  delay: 10
  changed_when: false

- name: gather information using ansible setup module
  ansible.builtin.setup:
    gather_subset:
      - distribution
      - network
      - python
      - processor
  timeout: 300

- name: gather services information
  ansible.builtin.service_facts:
  timeout: 300

- name: check ansible_python
  ydb_platform.ydb.warn:
    msg: "discovered ansible_python version is out of date and is not supported"
    that:
      - "ansible_python_version is version_compare('3.7', '<')"

- name: assert usage of systemd as an init system
  ansible.builtin.assert:
    that: ansible_service_mgr == 'systemd'
    msg: "only systemd service manager is supported"

- name: set collection level constants
  set_fact:
    ydb_dir: /opt/ydb

- name: Check current user
  ansible.builtin.command: whoami
  register: current_user

- name: Check conditions in variables (1. dynamic config)
  ansible.builtin.fail:
    msg: "Impossible to use ydb_enforce_user_token_requirement and ydb_request_client_certificate together"
  when: ydb_use_dynamic_config is defined and ydb_use_dynamic_config|bool and ydb_enforce_user_token_requirement|bool and ydb_request_client_certificate|bool
