---
# ydb database creation

- name: YDB database creation
  block:
    - name: Transfer the secrets
      copy: src=secret dest={{ ydb_dir }}/certs/secret
    - name: Run the database creation script
      command: "{{ ydb_dir }}/home/create_database.sh {{ inventory_hostname }} {{ ydb_database_name | default(ydb_dbname, true) }} {{ ydb_default_groups }}"
      become: true
      become_user: ydb
    - name: Cleanup the transferred secrets
      file: state=absent path={{ ydb_dir }}/certs/secret
  run_once: true
  tags:
    - create_database
