repositories: []

preferences: []

configs: []

packages:
  - bash-completion
  - ca-certificates
  - curl
  - dnsutils
  - gdisk
  - iptables
  - jq
  - logrotate
  - lsof
  - nvme-cli
  - procps
  - python3-apt
  - python3-pip
  - python3-requests
  - python3-virtualenv
  - rsync
  - strace
  - tar
  - tmux
  - tzdata
  - unzip
  - wget
  - xfsprogs
