- 

- name: restart timesyncd
  ansible.builtin.systemd:
    name: systemd-timesyncd.service
    state: restarted
  when: "'systemd-timesyncd' in services"

- name: restart journald
  ansible.builtin.systemd:
    name: systemd-journald.service
    state: restarted

- name: restart cron
  ansible.builtin.systemd:
    name: cron.service
    state: restarted
  when: "'cron' in services and 'crond' not in services"

- name: restart crond
  ansible.builtin.systemd:
    name: crond.service
    state: restarted
  when: "'crond' in services"

- name: apply kernel settings
  ansible.builtin.shell: sysctl -p

- name: restart cpufrequtils
  ansible.builtin.systemd:
    name: cpufrequtils.service
    state: restarted
