- name: Create the YDB server binary directory
  file: state=directory
        path="{{ ydb_dir }}/release/{{ ydb_version }}"
        recurse=true
        group=bin
        owner=root
        mode='0755'

- name: Install the YDB server binary package
  ansible.builtin.unarchive:
    creates: "{{ ydb_dir }}/release/{{ ydb_version }}/bin/ydbd"
    dest: "{{ ydb_dir }}/release/{{ ydb_version }}"
    group: bin
    owner: root
    src: "{{ ydbd_binary }}"
    extra_opts: "{{ ydb_unpack_options }}"

- name: Install the YDB CLI binary package
  ansible.builtin.unarchive:
    creates: "{{ ydb_dir }}/release/{{ ydb_version }}/bin/ydb"
    dest: "{{ ydb_dir }}/release/{{ ydb_version }}"
    group: bin
    owner: root
    src: "{{ ydbd_cli_binary }}"
    extra_opts: "{{ ydb_unpack_options }}"

- name: Symlink the YDB binaries
  file: path="{{ ydb_dir }}/bin"
        src="./release/{{ ydb_version }}/bin"
        state=link
        force=yes

- name: Symlink the YDB libraries
  file: path="{{ ydb_dir }}/lib"
        src="./release/{{ ydb_version }}/lib"
        state=link
        force=yes

- name: Create the YDB CLI default binary directory
  file: state=directory path={{ ydb_dir }}/home/ydb/bin recurse=true group=ydb owner=ydb mode='0700'

- name: Disable YDB CLI version checks
  copy: src=ydb-cli-config.json dest={{ ydb_dir }}/home/ydb/bin/config.json group=ydb owner=ydb mode='0644'
  register: ydb_is_installed

