- name: check if required variables are defined
  ansible.builtin.assert:
    that:
      - "{{ item }} is defined"
    fail_msg: "{{ item }} variable is required"
  loop:
    - {ydb_archive | ydbd_binary}
    - ydb_config

- name: install custom libidn from archive
  import_tasks:
    file: install_libidn_from_archive.yaml
  when: ydb_libidn_archive is defined

- name: install YDB server and cli binaries
  block:

  - name: install YDB server binary package from archive
    import_tasks:
      file: install_ydb_from_archive.yaml
    when: ydb_archive is defined 

  - name: download and install YDB server binary package from a release version number
    import_tasks:
      file: install_ydb_from_version.yaml
    when: ydb_version is defined and ydbd_binary is not defined and ydb_archive is not defined 

  - name: install YDB server binary package from source code
    import_tasks:
      file: install_ydb_from_source.yaml
    when: ydb_git_version is defined

  - name: install YDB binaries from files
    import_tasks:
      file: install_ydb_using_binary.yaml
    when: ydbd_binary is defined and ydb_cli_binary is defined

- name: Create the YDB CLI default binary directory
  file: state=directory path={{ ydb_dir }}/home/ydb/bin recurse=true group=ydb owner=ydb mode='0700'

- name: Disable YDB CLI version checks
  copy: src=ydb-cli-config.json dest={{ ydb_dir }}/home/ydb/bin/config.json group=ydb owner=ydb mode='0644'
  register: ydb_is_installed
