---

- name: Check ansible version
  when: "ansible_version.full is version('2.11', '<=')"
  ansible.builtin.fail:
    msg: "aborting playbook execution. Install Ansible 2.11 or newer. Current version is {{ ansible_version.full }}"

- name: Get PIDs of YDBD
  shell: pgrep ydbd | wc -l
  register: pids_of_ydbd

- name: Check presence of YDBD
  when: pids_of_ydbd.stdout != "0"
  ansible.builtin.fail:
    msg: "aborting playbook execution. Stop running YDB instances"

- name: Start script to listen YDB ports
  shell: "nohup nc -4 -6 -l {{ item }} -q 60 &"
  with_items: 
    - "{{ ydb_ports }}"

- name: Check connections between nodes
  wait_for:
    host: "{{ item.0 }}"
    port: "{{ item.1 }}"
    state: started
    delay: 0
    timeout: 1
  with_nested: 
    - "{{ groups['ydb'] }}"
    - "{{ ydb_ports }}"
