---


# PLAYBOOK: ydb_platform.ydb.initial_setup
# PROPOSE : This playbook is designed to install YDB cluster.
#           
# HOW TO USE:
#     Use https://github.com/ydb-platform/ydb-ansible-examples as an example to prepare Ansible
#     You will need proper:
#     - inventory
#     - YDB config
#     - SSL certificates
#
# EXAMPLE:
#
# ansible-playbook ydb_platform.ydb.initial_setup
#

- hosts: "{{ playbook_hosts | default('ydb') }}"
  become: true
  tasks:
    - name: check connectivity
      ansible.builtin.import_role:
        name: ydb_platform.ydb.check_connectivity

    - name: setup packages
      ansible.builtin.import_role:
        name: ydb_platform.ydb.packages
      when: ydb_tools_install|bool

    - name: configure system
      ansible.builtin.import_role:
        name: ydb_platform.ydb.system

    - name: setup ydb
      ansible.builtin.import_role:
        name: ydb_platform.ydb.ydbd
    
    - name: setup fq-connector
      ansible.builtin.import_role:
        name: ydb_platform.ydb.ydb_fq_connector
      when: ydb_install_fq_connector | default(false)

    - name: setup ydb static nodes
      ansible.builtin.import_role:
        name: ydb_platform.ydb.ydbd_static

    - name: setup ydb dynamic nodes
      ansible.builtin.import_role:
        name: ydb_platform.ydb.ydbd_dynamic
