- hosts: "{{ playbook_hosts | default('ydb') }}"
  become: true

  roles:
  - role: ydbd_rolling_static
    availability_mode: weak
    tags:
      - storage
      - static
  - role: ydbd_rolling_dynamic
    tags:
      - database
      - dynamic