- name: setup YDB connectivity on site
  hosts: "{{ ansible_play_hosts | default('ydb') }}"
  become: true
  tasks:
    - name: setup ipv4 connectivity
      ansible.builtin.import_role:
        name: ydb_platform.ydb.site_ipv4_connectivity
