- name: check if required variables are defined
  hosts: "{{ ansible_play_hosts | default('ydb') }}"

  tasks:
  - ansible.builtin.assert:
      that:
        - "{{ item.var1 is defined or item.var2 is defined }}"
      fail_msg: "Either {{ item.var1 }} or {{ item.var2 }} variable is required"
    loop:
      - { var1: "ydb_storage_node_cores", var2: "ydb_cores_static" }
      - { var1: "ydb_database_node_cores", var2: "ydb_cores_dynamic" }
  tags:
    - storage
    - static
    - database
    - dynamic
    - no_restart

- hosts: "{{ ansible_play_hosts | default('ydb') }}"
  become: true

  roles:
  - role: preflight
  - role: install_ydbd
  tags:
    - storage
    - static
    - database
    - dynamic
    - no_restart

- name: Restart YDB cluster
  become: true
  ansible.builtin.import_playbook: restart.yaml